### ISSUE TITLE
Different between multi_k and k

### ISSUE THREAD

**Issue by Sean0719** [wenxianxian/dgmvae#1]
Hi Wenxian, 

Sorry to disturb you. In the code there have multi_k and k, which confused me. Could you please give me a simple explanation of these two terms. As i understand, k is number of gaussian. So what is multi_k. Thanks.

**Comment by wenxianxian** [comment]
> Hi Wenxian,
> 
> Sorry to disturb you. In the code there have multi_k and k, which confused me. Could you please give me a simple explanation of these two terms. As i understand, k is number of gaussian. So what is multi_k. Thanks.

Hi Sean, we introduce multi_k to allow the multiple groups of independent latent variables. For example, if we have three groups of independent latent variables, the prior distribution is:
p(c_1,c_2,c_3,z_1,z_2,z_3)=p(c_1,z_1)p(c_2,z_2)p(c_3,z_3)=p(c_1)p(z_1|c_1)p(c_2)p(z_2|c_2)p(c_3)p(z_3|c_3), in which the p(c_1,z_1), p(c_2,z_2) and p(c_3,z_3) are all mixture of exponential family distribution.

**Comment by Sean0719** [comment]
Okay, I see. Thank you very much.
